### PR TITLE
Issue 8 ellipse rectangle data selection

### LINKED ISSUE #2: filtering the object based on coordinates
There are two ways we can implement and document of how filtering based on spatial coordinates

- object |> filter(rectangle(x, y, x_min, x_max, y_min, y_max)), for which you can build a wrapper on top object |> filter_rectangle(x_min, x_max, y_min, y_max)
- object |> filter(circle(x, y, x_center, y_center, radius)), for which you can build a wrapper on top object |> filter_circle(x_center, y_center, radius)

the function `rectangle` would be equivalent of x |> magrittr::between(x_min, x_max) & y |> magrittr::between(y_min, y_max) 

- with tidygave

see https://tidytranscriptomics-workshops.github.io/RMedicine2023_tidytranscriptomics/articles/main.html#filtering-based-on-gate

### LINKED ISSUE #8: Create a functionality for `tidySPE` mutate(gate1 = quare(...), gate2 = ellipse(...))
Similarly to `tidygate`,  we could create geometric selection functions that work within the `dplyr::mutate` method. For example.

```r
spatial_experiment_object = mutate(gate1 = rectangle(...), gate2 = ellipse(...))
```

We are looking for two functions, `rectangle` and `ellipse`. Those functions would return an array of boolean `TRUE` or `FALSE` depending on whether the dots/pixels are in the coordinates.

For rectangle, we could give the arguments
- spatial coordinate 1 
- spatial coordinate 2
- centre of the rectangle
- height
- width

Similarly for the ellipse

How do multiple gates interact? They don't each gate will create a column of boolean, the user will decide what do to with those multiple columns (i.e. intersection, union etc.).

### PR DESCRIPTION
**Pull request by qclayssen**
Enhance Spatial Data Handling with Ellipse and Rectangle Functions

Description:

This Pull Request introduces two new functions: ellipse and rectangle, designed to enhance the handling of spatial data in the tidySingleCellExperiment package. These functions allow users to define spatial regions of interest in their data, facilitating more precise analysis and visualization.

Key Features:

    Ellipse Function: Determines if points lie within a specified elliptical region. Parameters include spatial coordinates, center, and axes lengths.
    Rectangle Function: Identifies points within a rectangular region, based on spatial coordinates, center, height, and width.

These additions aim to provide users with more tools for spatial data analysis, improving both the flexibility and utility of the package.

Link to Issue: https://github.com/william-hutchison/tidySpatialExperiment/issues/8

### CODE REVIEW

**Comment by qclayssen** [comment]
@william-hutchison

**Comment by william-hutchison** [comment]
This all looks great, thank you for your contribution!

**Comment by stemangiola** [comment]
Wow that happened fast! No feedback or further requirements?

**Comment by stemangiola** [comment]
@william-hutchison can you please add this to the challenges and make sure that @qclayssen  is among the assignees?

**Pull request merged**
